name: (Windows) App Build
on:
    push:
    pull_request:
jobs:
    package:
        runs-on: windows-latest

        steps:
            -   name: Clone repository
                uses: actions/checkout@v4

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: "npm"

            -   name: Install dependencies
                run: npm install

            -   name: Delete old out/ directory
                run: "rm -rf out"

            -   name: Package app
                run: npm run package

            -   name: Make distributables
                run: npm run make -- --arch=x64
