name: (Windows) App Build
on:
    push:
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
jobs:
    package:
        runs-on: windows-latest

        steps:
            -   name: Clone repository
                uses: actions/checkout@v4

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: "npm"

            -   name: Install dependencies
                run: npm install

            -   name: Clean out directory
                run: Remove-Item -Recurse -Force out -ErrorAction SilentlyContinue
                shell: powershell

            -   name: Make distributables
                run: |
                    Remove-Item -Recurse -Force out -ErrorAction SilentlyContinue
                    npm run make -- --arch=x64
                shell: powershell