name: (macOS) Electron Forge App Packaging
on:
    push:
        branches:
            - *
    pull_request:
        branches:
            - *
jobs:
    package:
        runs-on: macos-latest

        steps:
            -   name: Clone repository
                uses: actions/checkout@v4

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 18
                    cache: "npm"

            -   name: Install dependencies
                run: npm install

            -   name: Package app
                run: npm run package

            -   name: Make distributables
                run: npm run make
